various sommelier tweaks

diff --git a/scripts/sommelier b/scripts/sommelier
--- a/scripts/sommelier
+++ b/scripts/sommelier
@@ -7,6 +7,16 @@ If you encounter issues please report them on the ${TITLE} snap issue tracker:
 
 https://github.com/diddlesnaps/gog-galaxy-wine/issues"
 
+needs_update=true
+
+. $SNAP_USER_DATA/.last_revision 2>/dev/null || true
+if [ "$SNAP_DESKTOP_LAST_REVISION" = "$SNAP_REVISION" ]; then
+  needs_update=false
+fi
+
+# Set $REALHOME to the users real home directory
+REALHOME=`getent passwd $UID | cut -d ':' -f 6`
+
 # https://stackoverflow.com/questions/4023830/how-to-compare-two-strings-in-dot-separated-version-format-in-bash
 vercomp() {
     if [[ $1 == $2 ]]
@@ -132,19 +142,21 @@ if [ -n "${DLLOVERRIDES}" ]; then
   export WINEDLLOVERRIDES="${DLLOVERRIDES}"
 fi
 
-if [ "$SNAP_ARCH" == "amd64" ]; then
+if [ "$SNAP_ARCH" = "amd64" ]; then
   export WINEARCH=win64
   export WINE=wine64
   export WINELOADER=$SNAP/bin/wine64
   export WINEDLLPATH=$SNAP/lib64/wine/fakedlls
   export ARCH="x86_64-linux-gnu"
-  export LD_LIBRARY_PATH="$SNAP/lib/i386-linux-gnu:$SNAP/usr/lib/i386-linux-gnu:$SNAP/lib64:$LD_LIBRARY_PATH"
-else
+elif [ "$SNAP_ARCH" = "i386" ]; then
   export WINEARCH=win32
   export WINE=wine
   export WINELOADER=$SNAP/bin/wine
   export WINEDLLPATH=$SNAP/lib/wine/fakedlls
-  export ARCH="$SNAP_ARCH-linux-gnu"
+  export ARCH="i386-linux-gnu"
+else
+  echo "Host architecture ($SNAP_ARCH) unsupported."
+  exit 1
 fi
 
 export WINEVERPATH=$SNAP
@@ -154,7 +166,12 @@ export winepath=$SNAP/bin/winepath
 export WINEPREFIX="$SNAP_USER_COMMON/.wine"
 
 #export WINEDEBUG=-all
-export LD_LIBRARY_PATH="$SNAP/lib:$SNAP/lib/$ARCH:$SNAP/usr/lib:$SNAP/usr/lib/$ARCH:$LD_LIBRARY_PATH"
+export LD_LIBRARY_PATH="$SNAP/lib/$ARCH:$SNAP/lib:$SNAP/usr/lib/$ARCH:$SNAP/usr/lib"
+if [ "$SNAP_ARCH" = "amd64" ]; then
+  append_dir LD_LIBRARY_PATH $SNAP/lib64
+  append_dir LD_LIBRARY_PATH $SNAP/lib/i386-linux-gnu
+  append_dir LD_LIBRARY_PATH $SNAP/usr/lib/i386-linux-gnu
+fi
 
 # XKB config
 export XKB_CONFIG_ROOT=$SNAP/usr/share/X11/xkb
@@ -168,13 +185,17 @@ export XCURSOR_PATH=$SNAP/usr/share/icons
 
 # SAMBA Libs for ntlm_auth to function
 append_dir LD_LIBRARY_PATH $SNAP/usr/lib/$ARCH/samba
+[ "$SNAP_ARCH" = "amd64" ] && append_dir LD_LIBRARY_PATH $SNAP/usr/lib/i386-linux-gnu/samba
 
 # Mesa Libs for OpenGL support
 append_dir LD_LIBRARY_PATH $SNAP/usr/lib/$ARCH/mesa
 append_dir LD_LIBRARY_PATH $SNAP/usr/lib/$ARCH/mesa-egl
+[ "$SNAP_ARCH" = "amd64" ] && append_dir LD_LIBRARY_PATH $SNAP/usr/lib/i386-linux-gnu/mesa
+[ "$SNAP_ARCH" = "amd64" ] && append_dir LD_LIBRARY_PATH $SNAP/usr/lib/i386-linux-gnu/mesa-egl
 
 # Tell libGL where to find the drivers
 export LIBGL_DRIVERS_PATH=$SNAP/usr/lib/$ARCH/dri
+[ "$SNAP_ARCH" = "amd64" ] && append_dir LIBGL_DRIVERS_PATH $SNAP/usr/lib/i386-linux-gnu/dri
 append_dir LD_LIBRARY_PATH $LIBGL_DRIVERS_PATH
 
 # Workaround in snapd for proprietary nVidia drivers mounts the drivers in
@@ -185,9 +206,7 @@ append_dir LD_LIBRARY_PATH /var/lib/snapd/lib/gl
 
 # Pulseaudio export
 append_dir LD_LIBRARY_PATH $SNAP/usr/lib/$ARCH/pulseaudio
-if [ "$SNAP_ARCH" == "amd64" ]; then
-    append_dir LD_LIBRARY_PATH $SNAP/usr/lib/i386-linux-gnu/pulseaudio
-fi
+[ "$SNAP_ARCH" = "amd64" ] && append_dir LD_LIBRARY_PATH $SNAP/usr/lib/i386-linux-gnu/pulseaudio
 
 # EGL vendor files on glvnd enabled systems
 [ -d /var/lib/snapd/lib/glvnd/egl_vendor.d ] && \
@@ -238,7 +257,42 @@ fi
 
 # Font Config and themes
 export FONTCONFIG_PATH=$SNAP/etc/fonts/conf.d
-#export FONTCONFIG_FILE=$XDG_CONFIG_HOME/fontconfig/fonts.conf
+export FONTCONFIG_FILE=$XDG_CONFIG_HOME/fontconfig/fonts.conf
+
+function make_user_fontconfig {
+  echo "<fontconfig>"
+  if [ -d $REALHOME/.local/share/fonts ]; then
+    echo "  <dir>$REALHOME/.local/share/fonts</dir>"
+  fi
+  if [ -d $REALHOME/.fonts ]; then
+    echo "  <dir>$REALHOME/.fonts</dir>"
+  fi
+  for d in "${data_dirs_array[@]}"; do
+    if [ -d "$d/fonts" ]; then
+      echo "  <dir>$d/fonts</dir>"
+    fi
+  done
+  echo '  <include ignore_missing="yes">conf.d</include>'
+  # We need to include this default cachedir first so that caching
+  # works: without it, fontconfig will try to write to the real user home
+  # cachedir and be blocked by AppArmor.
+  echo '  <cachedir prefix="xdg">fontconfig</cachedir>'
+  if [ -d $REALHOME/.cache/fontconfig ]; then
+    echo "  <cachedir>$REALHOME/.cache/fontconfig</cachedir>"
+  fi
+  echo "</fontconfig>"
+}
+
+if [ $needs_update = true ]; then
+  rm -rf $XDG_DATA_HOME/{fontconfig,fonts,fonts-*,themes,.themes}
+  mkdir -p $XDG_CONFIG_HOME/fontconfig
+  make_user_fontconfig > $FONTCONFIG_FILE
+
+  # the themes symlink are needed for GTK 3.18 when the prefix isn't changed
+  # GTK 3.20 looks into XDG_DATA_DIR which has connected themes.
+  ln -sf $SNAP/usr/share/themes $XDG_DATA_HOME
+  ln -sfn $SNAP/usr/share/themes $SNAP_USER_DATA/.themes
+fi
 
 # Gdk-pixbuf loaders
 export GDK_PIXBUF_MODULE_FILE=$XDG_CACHE_HOME/gdk-pixbuf-loaders.cache
@@ -272,6 +326,8 @@ else
   # Notification
   notify-send --icon "${SNAP}/meta/gui/gog-galaxy.png" --expire-time=15000 "${TITLE}" "${NOTICE}"
 fi
+
+[ $needs_update = true ] && echo "SNAP_DESKTOP_LAST_REVISION=$SNAP_REVISION" > $SNAP_USER_DATA/.last_revision
 
 # Launch wineboot/winecfg/winetricks if requested.
 # If the executable exists then launch it otherwise install it then lauch it.
